### PR TITLE
Adjust coding style of include path

### PR DESCRIPTION
**Pull request by wcwang**
Adjust the format of include path for all platforms according to the coding style. In the #include directive, only the header file name (or prefixed with the name of the subdirectory under the include path) is reserved.

* Add header search paths to the project file and remove the redundant relative paths in headers, implementation and resource files
* Update the #include directives for Windows, macOS, Linux and NetBSD platforms

### CODE REVIEW

**Comment by krytarowski** [comment]
Did you test NetBSD? param.h and types.h must go first.

**Comment by wcwang** [comment]
> Did you test NetBSD? param.h and types.h must go first.

Thanks for your attention. We don't have NetBSD environment to verify it yet. Do you have time to test it on NetBSD? If possible, you may base on my patch and complement the Makefile part for header search path and I will cancel my patch then. Thanks a lot.

**Comment by krytarowski** [comment]
Please revert all reordering of kernel headers for NetBSD and add `CPPFLAGS+= -I$(src)/../../include -I$(src)/../../core/include` in the Makefile. Then I will build test it.

**Comment by wcwang** [comment]
Thanks for your reply. I have updated the patch for NetBSD. Could you help to build it? If there is any issue, please let me know. Thanks again.

**Comment by wcwang** [comment]
@krytarowski, have you ever verified the build on NetBSD? May I merge this PR then? Thanks a lot.

**Comment by wcwang** [comment]
@krytarowski, sorry for bothering you. As HAXM is approaching to release, if you do not have time to verify the build, could you review the updated patch? If the NetBSD code review passes, we can merge it first. Thanks a lot.

**Comment by krytarowski** [comment]
Testing now.

**Comment by krytarowski** [comment]
I had to do this on top of this pull-request in order to make it buildable.

```
diff --git a/platforms/netbsd/Makefile b/platforms/netbsd/Makefile
index 4b601de..8853550 100644
--- a/platforms/netbsd/Makefile
+++ b/platforms/netbsd/Makefile
@@ -2,7 +2,8 @@ S?=	/usr/src/sys
 
 KMOD=	haxm
 
-CPPFLAGS+= -I$(src)/../../include -I$(src)/../../core/include
+CFLAGS+=-Wno-error=address-of-packed-member
+CPPFLAGS+= -I../../include -I../../core/include
 
 # toplevel
 SRCS+=	components.c

```

**Comment by wcwang** [comment]
@krytarowski, thanks for your verification. I have updated the patch of NetBSD and will merge it later. Thanks.

**Review by hyuan3 — APPROVED** [review]

**Pull request merged**
