### PR TITLE
Bump version for 7.6.0 release

### PR DESCRIPTION
**Pull request by wcwang**
Signed-off-by: Wenchao Wang <wenchao.wang@intel.com>

### CODE REVIEW

**Comment by krytarowski** [comment]
Please hold on, I want to add missing NetBSD support for new CPUID feature.

**Comment by krytarowski** [comment]
Blocker: https://github.com/intel/haxm/pull/281

**Comment by wcwang** [comment]
@krytarowski, thanks for your contribution for NetBSD. Your patches made NetBSD always updated for HAXM. However, according to our release progress, we had launched the release process and QA team had started to test yesterday. Sorry for not including your immediate update in this release. We will leave more time for community activity next time. Never mind, we are going to plan the next release soon and will add NetBSD support definitely. This version is just a landing for `HAX_VCPU_IOCTL_SET_CPUID`, quite a few things, such as in-depth CPUID features setting, common header for POSIX, need to be accomplished. Your future contribution will be welcome.

**Comment by krytarowski** [comment]
If this version is just for landing one feature, it shall not regress  in generic functionality. Right now one of the supported targets is not buildable.

**Comment by krytarowski** [comment]
But landing this in 7.6.1 is fine too.

**Comment by wcwang** [comment]
Thanks for your reply. You are right. The build checks in Travis CI only cover 3 hosts. We have limited resource to cover NetBSD test. According to the previous commitment, we have to deliver HAXM release with this interface to our customers. Next time we will try to reserve more time for community to avoid such issue happened. Thanks for your understanding.

**Comment by wcwang** [comment]
We will merge #281 and another patch and restart the release process. So cancel this release request first.

**Pull request closed without merging**
