### PR TITLE
GRUPO HUERTA/.github

### PR DESCRIPTION
**Pull request by HUERTAGROUP**
…SSUE_TEMPLATE/bug_report.md

### CODE REVIEW

**Comment by wayne-ma** [comment]
ok to verify

**Comment by wayne-ma** [comment]
ok to verify

**Comment by wayne-ma** [comment]
ok to verify

**Comment by wayne-ma** [comment]
Ok to verify

**Comment by wayne-ma** [comment]
Ok to verify

**Comment by xianxiaoyin** [comment]
Ok to verify

**Comment by xianxiaoyin** [comment]
OK to verify

**Comment by xianxiaoyin** [comment]
verify

**Comment by xianxiaoyin** [comment]
OK to verify

**Comment by wayne-ma** [comment]
Ok to verify

**Comment by xianxiaoyin** [comment]
Ok to verify

**Comment by xianxiaoyin** [comment]
Ok to verify

**Comment by xianxiaoyin** [comment]
OK to verify

**Pull request closed without merging**
